### PR TITLE
Update dependencies, fix build

### LINKED ISSUE #652: Project has out of date dependencies and './gradlew clean build test' fails
**Describe the bug**
'./gradlew clean build test' fails with 9 errors

**To Reproduce**
Follow README and execute './gradlew clean build test'

**Expected behavior**
Builds and tests without error

**Screenshots**

```
9 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':build-info-api:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
15 actionable tasks: 12 executed, 3 up-to-date
```

**Versions**
- Extractor version: 2.36.3 (Latest)
- Operating system: All
- Artifactory Version: 4.28.3 (Latest)

**Additional context**
Project also has many out of date dependencies.

### PR DESCRIPTION
**Pull request by elevenfive**
- [X] All [tests](https://ci.appveyor.com/project/jfrog-ecosystem/build-info) passed. If this feature is not already covered by the tests, I added new tests.
-----

Have run all the tests that don't require a docker instance running.  If someone else has one handy and can test this, it would be appreciated!

Fixes #652

### CODE REVIEW

**Comment by elevenfive** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by elevenfive** [comment]
recheck

**Comment by alivesubstance** [comment]
Guys, any updates on this PR?

**Review by yahavi — APPROVED** [review]
Thanks, @elevenfive!

**Comment by yahavi** [comment]
@elevenfive,
After merging this PR, I noticed that the publish tasks failed. 
We'd appreciate it if you could create a new PR after verifying that the `publishToMavenLocal` task passes.

By the way - what is the original reason that the build failed for you? Did you compile with JDK 8?
Thanks.

**Comment by elevenfive** [comment]
Hi I was using JDK 11, are you able to run this build at all?  Upgrade to Gradle 7 is the reason, I will push with Gradle 6.  Gradle 7 migration will be more involved and beyond my current expertise with Gradle plugins.

**Comment by kilinochi** [comment]
hello! and when you are going to collect new realize ?
